USE rvs_fishworld;

CREATE TABLE IF NOT EXISTS csupp_d (
    csupp_d_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    supplier_code VARCHAR(30) NOT NULL,
    product_code VARCHAR(30) NOT NULL,
    price DECIMAL(14,4) NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_csupp_d_supplier_product (supplier_code, product_code)
);

CREATE TABLE IF NOT EXISTS approval (
    approval_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    pw VARCHAR(100) NOT NULL,
    pw_user VARCHAR(100) NOT NULL DEFAULT '',
    user_name VARCHAR(150) NOT NULL DEFAULT '',
    remarks VARCHAR(255),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_approval_pw_user (pw, pw_user)
);

CREATE TABLE IF NOT EXISTS stop_4ever (
    prod_no VARCHAR(30) PRIMARY KEY,
    remarks VARCHAR(255),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS plimit (
    plimit_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    prod_no VARCHAR(30) NOT NULL,
    supp_code VARCHAR(30) NOT NULL,
    qty DECIMAL(12,2) NOT NULL DEFAULT 0,
    price DECIMAL(14,4) NOT NULL DEFAULT 0,
    remarks VARCHAR(255),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_plimit_prod_supplier (prod_no, supp_code)
);
