USE rvs_fishworld;

CREATE TABLE IF NOT EXISTS app_users (
    user_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    display_name VARCHAR(150) NOT NULL,
    password_hash VARCHAR(255),
    must_reset_password BOOLEAN NOT NULL DEFAULT TRUE,
    rights_csv LONGTEXT,
    raw_flags_csv LONGTEXT,
    photo_hint VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    last_login_at DATETIME,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS company_profile (
    company_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    company_name VARCHAR(255) NOT NULL,
    company_address VARCHAR(255),
    tin VARCHAR(50),
    sss_no VARCHAR(50),
    phone VARCHAR(100),
    fax VARCHAR(100),
    email VARCHAR(150),
    executive_name VARCHAR(150),
    is_read_only BOOLEAN NOT NULL DEFAULT FALSE,
    auto_ac BOOLEAN NOT NULL DEFAULT FALSE,
    updated_by VARCHAR(100),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_events (
    audit_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    event_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    username VARCHAR(100),
    action_type VARCHAR(80) NOT NULL,
    module_name VARCHAR(150) NOT NULL,
    reference_no VARCHAR(120),
    details TEXT
);

CREATE TABLE IF NOT EXISTS backup_jobs (
    backup_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    file_path VARCHAR(500) NOT NULL,
    status VARCHAR(40) NOT NULL,
    details TEXT
);

CREATE TABLE IF NOT EXISTS maintenance_runs (
    maintenance_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    run_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    run_by VARCHAR(100),
    operation_name VARCHAR(120) NOT NULL,
    status VARCHAR(40) NOT NULL,
    details TEXT
);

CREATE TABLE IF NOT EXISTS salesmen (
    salesman_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    salesman_code VARCHAR(30) NOT NULL UNIQUE,
    salesman_name VARCHAR(150) NOT NULL,
    phone VARCHAR(100),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS areas (
    area_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    area_code VARCHAR(30) NOT NULL UNIQUE,
    area_name VARCHAR(150) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS banks (
    bank_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    bank_code VARCHAR(30) NOT NULL UNIQUE,
    bank_name VARCHAR(150) NOT NULL,
    account_no VARCHAR(80),
    branch_name VARCHAR(150),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS net_prices (
    net_price_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    product_code VARCHAR(30) NOT NULL,
    customer_code VARCHAR(30),
    currency_code VARCHAR(20),
    net_price DECIMAL(14,4) NOT NULL DEFAULT 0,
    remarks VARCHAR(255),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS stop_of_week (
    stop_week_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    product_code VARCHAR(30) NOT NULL,
    week_label VARCHAR(50),
    remarks VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS contract_prices (
    contract_price_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    contract_type VARCHAR(40) NOT NULL,
    product_code VARCHAR(30) NOT NULL,
    party_code VARCHAR(30) NOT NULL,
    price DECIMAL(14,4) NOT NULL DEFAULT 0,
    remarks VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS special_of_week (
    special_week_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    product_code VARCHAR(30) NOT NULL,
    special_price DECIMAL(14,4) NOT NULL DEFAULT 0,
    start_date DATE,
    end_date DATE,
    remarks VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS flat_prices (
    flat_price_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    supplier_code VARCHAR(30) NOT NULL,
    product_code VARCHAR(30) NOT NULL,
    flat_price DECIMAL(14,4) NOT NULL DEFAULT 0,
    remarks VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS generic_documents (
    document_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    document_type VARCHAR(80) NOT NULL,
    document_no VARCHAR(60) NOT NULL,
    document_date DATE NOT NULL,
    party_code VARCHAR(40),
    party_name VARCHAR(200),
    location_code VARCHAR(40),
    extra_ref VARCHAR(80),
    amount DECIMAL(14,4) NOT NULL DEFAULT 0,
    status VARCHAR(40) NOT NULL DEFAULT 'OPEN',
    notes TEXT,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_document_type_no (document_type, document_no)
);
